// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bridgelink_pytorch.proto
#ifndef GRPC_bridgelink_5fpytorch_2eproto__INCLUDED
#define GRPC_bridgelink_5fpytorch_2eproto__INCLUDED

#include "bridgelink_pytorch.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace bridgelink {

class PyTorchService final {
 public:
  static constexpr char const* service_full_name() {
    return "bridgelink.PyTorchService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::bridgelink::CudaAvailableResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>> AsyncIsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>>(AsyncIsCudaAvailableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>> PrepareAsyncIsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>>(PrepareAsyncIsCudaAvailableRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::bridgelink::CudaDeviceCountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>> AsyncGetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>>(AsyncGetCudaDeviceCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>> PrepareAsyncGetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>>(PrepareAsyncGetCudaDeviceCountRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>* AsyncIsCudaAvailableRaw(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaAvailableResponse>* PrepareAsyncIsCudaAvailableRaw(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>* AsyncGetCudaDeviceCountRaw(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgelink::CudaDeviceCountResponse>* PrepareAsyncGetCudaDeviceCountRaw(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::bridgelink::CudaAvailableResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>> AsyncIsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>>(AsyncIsCudaAvailableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>> PrepareAsyncIsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>>(PrepareAsyncIsCudaAvailableRaw(context, request, cq));
    }
    ::grpc::Status GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::bridgelink::CudaDeviceCountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>> AsyncGetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>>(AsyncGetCudaDeviceCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>> PrepareAsyncGetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>>(PrepareAsyncGetCudaDeviceCountRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response, std::function<void(::grpc::Status)>) override;
      void IsCudaAvailable(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCudaDeviceCount(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>* AsyncIsCudaAvailableRaw(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaAvailableResponse>* PrepareAsyncIsCudaAvailableRaw(::grpc::ClientContext* context, const ::bridgelink::CudaAvailableRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>* AsyncGetCudaDeviceCountRaw(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bridgelink::CudaDeviceCountResponse>* PrepareAsyncGetCudaDeviceCountRaw(::grpc::ClientContext* context, const ::bridgelink::CudaDeviceCountRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_IsCudaAvailable_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCudaDeviceCount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status IsCudaAvailable(::grpc::ServerContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response);
    virtual ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsCudaAvailable(::grpc::ServerContext* context, ::bridgelink::CudaAvailableRequest* request, ::grpc::ServerAsyncResponseWriter< ::bridgelink::CudaAvailableResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCudaDeviceCount(::grpc::ServerContext* context, ::bridgelink::CudaDeviceCountRequest* request, ::grpc::ServerAsyncResponseWriter< ::bridgelink::CudaDeviceCountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_IsCudaAvailable<WithAsyncMethod_GetCudaDeviceCount<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bridgelink::CudaAvailableRequest, ::bridgelink::CudaAvailableResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bridgelink::CudaAvailableRequest* request, ::bridgelink::CudaAvailableResponse* response) { return this->IsCudaAvailable(context, request, response); }));}
    void SetMessageAllocatorFor_IsCudaAvailable(
        ::grpc::MessageAllocator< ::bridgelink::CudaAvailableRequest, ::bridgelink::CudaAvailableResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bridgelink::CudaAvailableRequest, ::bridgelink::CudaAvailableResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsCudaAvailable(
      ::grpc::CallbackServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::bridgelink::CudaDeviceCountRequest, ::bridgelink::CudaDeviceCountResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bridgelink::CudaDeviceCountRequest* request, ::bridgelink::CudaDeviceCountResponse* response) { return this->GetCudaDeviceCount(context, request, response); }));}
    void SetMessageAllocatorFor_GetCudaDeviceCount(
        ::grpc::MessageAllocator< ::bridgelink::CudaDeviceCountRequest, ::bridgelink::CudaDeviceCountResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bridgelink::CudaDeviceCountRequest, ::bridgelink::CudaDeviceCountResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCudaDeviceCount(
      ::grpc::CallbackServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_IsCudaAvailable<WithCallbackMethod_GetCudaDeviceCount<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsCudaAvailable(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCudaDeviceCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IsCudaAvailable(context, request, response); }));
    }
    ~WithRawCallbackMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsCudaAvailable(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCudaDeviceCount(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCudaDeviceCount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IsCudaAvailable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IsCudaAvailable() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bridgelink::CudaAvailableRequest, ::bridgelink::CudaAvailableResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bridgelink::CudaAvailableRequest, ::bridgelink::CudaAvailableResponse>* streamer) {
                       return this->StreamedIsCudaAvailable(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IsCudaAvailable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IsCudaAvailable(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaAvailableRequest* /*request*/, ::bridgelink::CudaAvailableResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIsCudaAvailable(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bridgelink::CudaAvailableRequest,::bridgelink::CudaAvailableResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCudaDeviceCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCudaDeviceCount() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bridgelink::CudaDeviceCountRequest, ::bridgelink::CudaDeviceCountResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bridgelink::CudaDeviceCountRequest, ::bridgelink::CudaDeviceCountResponse>* streamer) {
                       return this->StreamedGetCudaDeviceCount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCudaDeviceCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCudaDeviceCount(::grpc::ServerContext* /*context*/, const ::bridgelink::CudaDeviceCountRequest* /*request*/, ::bridgelink::CudaDeviceCountResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCudaDeviceCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bridgelink::CudaDeviceCountRequest,::bridgelink::CudaDeviceCountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_IsCudaAvailable<WithStreamedUnaryMethod_GetCudaDeviceCount<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_IsCudaAvailable<WithStreamedUnaryMethod_GetCudaDeviceCount<Service > > StreamedService;
};

}  // namespace bridgelink


#endif  // GRPC_bridgelink_5fpytorch_2eproto__INCLUDED
