// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bridge.proto

#include "bridge.pb.h"
#include "bridge.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace bridgeserver {

static const char* BridgeServerService_method_names[] = {
  "/bridgeserver.BridgeServerService/SayHello",
  "/bridgeserver.BridgeServerService/StreamNumbers",
};

std::unique_ptr< BridgeServerService::Stub> BridgeServerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BridgeServerService::Stub> stub(new BridgeServerService::Stub(channel, options));
  return stub;
}

BridgeServerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(BridgeServerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamNumbers_(BridgeServerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status BridgeServerService::Stub::SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::bridgeserver::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void BridgeServerService::Stub::async::SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void BridgeServerService::Stub::async::SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>* BridgeServerService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bridgeserver::HelloReply, ::bridgeserver::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>* BridgeServerService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::bridgeserver::StreamReply>* BridgeServerService::Stub::StreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::bridgeserver::StreamReply>::Create(channel_.get(), rpcmethod_StreamNumbers_, context, request);
}

void BridgeServerService::Stub::async::StreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest* request, ::grpc::ClientReadReactor< ::bridgeserver::StreamReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::bridgeserver::StreamReply>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamNumbers_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>* BridgeServerService::Stub::AsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::bridgeserver::StreamReply>::Create(channel_.get(), cq, rpcmethod_StreamNumbers_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>* BridgeServerService::Stub::PrepareAsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::bridgeserver::StreamReply>::Create(channel_.get(), cq, rpcmethod_StreamNumbers_, context, request, false, nullptr);
}

BridgeServerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BridgeServerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BridgeServerService::Service, ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BridgeServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bridgeserver::HelloRequest* req,
             ::bridgeserver::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BridgeServerService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< BridgeServerService::Service, ::bridgeserver::StreamRequest, ::bridgeserver::StreamReply>(
          [](BridgeServerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bridgeserver::StreamRequest* req,
             ::grpc::ServerWriter<::bridgeserver::StreamReply>* writer) {
               return service->StreamNumbers(ctx, req, writer);
             }, this)));
}

BridgeServerService::Service::~Service() {
}

::grpc::Status BridgeServerService::Service::SayHello(::grpc::ServerContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BridgeServerService::Service::StreamNumbers(::grpc::ServerContext* context, const ::bridgeserver::StreamRequest* request, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bridgeserver

