// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bridge.proto
#ifndef GRPC_bridge_2eproto__INCLUDED
#define GRPC_bridge_2eproto__INCLUDED

#include "bridge.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace bridgeserver {

class BridgeServerService final {
 public:
  static constexpr char const* service_full_name() {
    return "bridgeserver.BridgeServerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::bridgeserver::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::bridgeserver::StreamReply>> StreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::bridgeserver::StreamReply>>(StreamNumbersRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>> AsyncStreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>>(AsyncStreamNumbersRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>> PrepareAsyncStreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>>(PrepareAsyncStreamNumbersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void StreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest* request, ::grpc::ClientReadReactor< ::bridgeserver::StreamReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bridgeserver::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::bridgeserver::StreamReply>* StreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>* AsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::bridgeserver::StreamReply>* PrepareAsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::bridgeserver::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::bridgeserver::StreamReply>> StreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::bridgeserver::StreamReply>>(StreamNumbersRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>> AsyncStreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>>(AsyncStreamNumbersRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>> PrepareAsyncStreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>>(PrepareAsyncStreamNumbersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamNumbers(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest* request, ::grpc::ClientReadReactor< ::bridgeserver::StreamReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bridgeserver::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::bridgeserver::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::bridgeserver::StreamReply>* StreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>* AsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::bridgeserver::StreamReply>* PrepareAsyncStreamNumbersRaw(::grpc::ClientContext* context, const ::bridgeserver::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamNumbers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response);
    virtual ::grpc::Status StreamNumbers(::grpc::ServerContext* context, const ::bridgeserver::StreamRequest* request, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::bridgeserver::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::bridgeserver::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamNumbers(::grpc::ServerContext* context, ::bridgeserver::StreamRequest* request, ::grpc::ServerAsyncWriter< ::bridgeserver::StreamReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_StreamNumbers<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bridgeserver::HelloRequest* request, ::bridgeserver::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::bridgeserver::StreamRequest, ::bridgeserver::StreamReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bridgeserver::StreamRequest* request) { return this->StreamNumbers(context, request); }));
    }
    ~WithCallbackMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::bridgeserver::StreamReply>* StreamNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_StreamNumbers<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamNumbers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamNumbers(context, request); }));
    }
    ~WithRawCallbackMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamNumbers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bridgeserver::HelloRequest, ::bridgeserver::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::bridgeserver::HelloRequest* /*request*/, ::bridgeserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bridgeserver::HelloRequest,::bridgeserver::HelloReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamNumbers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamNumbers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::bridgeserver::StreamRequest, ::bridgeserver::StreamReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::bridgeserver::StreamRequest, ::bridgeserver::StreamReply>* streamer) {
                       return this->StreamedStreamNumbers(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamNumbers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamNumbers(::grpc::ServerContext* /*context*/, const ::bridgeserver::StreamRequest* /*request*/, ::grpc::ServerWriter< ::bridgeserver::StreamReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamNumbers(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::bridgeserver::StreamRequest,::bridgeserver::StreamReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamNumbers<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithSplitStreamingMethod_StreamNumbers<Service > > StreamedService;
};

}  // namespace bridgeserver


#endif  // GRPC_bridge_2eproto__INCLUDED
